---
system_networks_interfaces:
  - name: ens6
    description: Public network
    bootproto: dhcp
  - name: ens7
    description: Private network
    bootproto: static
    ip: 192.168.250.53/24
    routes:
      - network: 192.168.250.0/24
