---
- name: Archlinux - Reboot if kernel has been updated
  ansible.builtin.shell:
    cmd: >
      set -o pipefail;
      file -bL /boot/vmlinuz-linux | grep -oP '(?<=version )[^ ]*'
  register: _system_installed_kernel
  changed_when: _system_installed_kernel.stdout != ansible_facts.kernel
  check_mode: false
  notify: "{{ system_reboot_handler }}"

- name: Archlinux - Set fact system_needs_reboot
  ansible.builtin.set_fact:
    system_needs_reboot: "{{ _system_installed_kernel.stdout != ansible_facts.kernel }}"
