---
- name: Show useful facts
  vars:
    useful_facts:
      ansible_facts.pkg_mgr: "{{ ansible_facts.pkg_mgr }}"
      ansible_facts.distribution: "{{ ansible_facts.distribution }}"
      ansible_facts.os_family: "{{ ansible_facts.os_family }}"
  ansible.builtin.debug:
    var: useful_facts

- name: System not recognized
  ansible.builtin.fail:
    msg: This system is not recognized
