---
# WARNING :
#
# Do not use a link to ../default/molecule.yml
# It will break the additional devices and the Ansible inventory
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true
platforms:
  # Revoked
  # - name: archlinux
  #   box: archlinux/archlinux
  #   interfaces: &interfaces
  #     - auto_config: false
  #       network_name: private_network
  #       type: dhcp
  #   provider_raw_config_args: &provider_raw_config
  #     - "cpu_mode = 'host-passthrough'"
  #     - "disk_bus = 'virtio'"
  #     - "nic_model_type = 'virtio'"
  #     - "video_type = 'virtio'"
  #     - "disk_driver :cache => 'writeback'"
  #     - "storage :file, bus: 'virtio', cache: 'writeback'"
  #   instance_raw_config_args:
  #     - 'vm.disk :disk, size: "1GB", name: "vdb"'
  #     - 'vm.provision :shell, inline: "pacman -Sy --noconfirm git net-tools python3 sudo unzip which"'

  # Very very long build due to old box
  # - name: gentoo
  #   box: generic-x64/gentoo
  #   cpus: 4
  #   memory: 8192
  #   interfaces: *interfaces
  #   provider_raw_config_args:
  #     - "cpu_mode = 'host-passthrough'"
  #     - "nic_model_type = 'virtio'"
  #     - "video_type = 'virtio'"
  #     - "disk_driver :cache => 'writeback'"
  #     - "storage :file, bus: 'virtio', cache: 'writeback'"
  #   instance_raw_config_args:
  #     - 'vm.disk :disk, size: "1GB", name: "vdb"'


  # Debian like
  - name: bullseye  # EOL 2026-08-31
    box: debian/bullseye64
    groups:
      - debian_like
      - debian
    interfaces: &interfaces
      - auto_config: false
        network_name: private_network
        type: dhcp
    provider_raw_config_args: &provider_raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    instance_raw_config_args: &instance_raw_config
      - 'vm.disk :disk, size: "1GB", name: "vdb"'
  - name: bookworm  # EOL 2028-06-10
    box: debian/bookworm64
    groups:
      - debian_like
      - debian
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
  - name: trixie
    box: debian/testing64
    groups:
      - debian_like
      - debian
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
  - name: jammy     # EOL 2027-04-01
    box: cloud-image/ubuntu-22.04
    groups:
      - debian_like
      - ubuntu
    memory: 2048
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
  - name: noble     # EOL 2029-04-25
    box: alvistack/ubuntu-24.04
    groups:
      - debian_like
      - ubuntu
    memory: 2048
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config

  # RedHat like
  - name: centos9s  # EOL 2027-05-31
    box: generic-x64/centos9s
    groups:
      - redhat_like
    memory: 2048
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
  # - name: centos10s  # EOL 2027-05-31
  #   box: alvistack/centos-10-stream
  #   groups:
  #     - redhat_like
  #   memory: 2048
  #   interfaces: *interfaces
  #   provider_raw_config_args: *provider_raw_config
  #   instance_raw_config_args: *instance_raw_config
  - name: alma9     # EOL 2027-05-31
    box: generic-x64/alma9
    groups:
      - redhat_like
    memory: 2048
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
  - name: fedora41  # EOL 2025-11-19
    box: fedora/41-cloud-base
    groups:
      - redhat_like
    memory: 2048
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
  - name: fedora42  # EOL 2026-05-13
    box: alvistack/fedora-42
    groups:
      - redhat_like
    memory: 2048
    interfaces: *interfaces
    provider_raw_config_args: *provider_raw_config
    instance_raw_config_args: *instance_raw_config
lint: ansible-lint
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: inventory/group_vars
      host_vars: inventory/host_vars
verifier:
  name: ansible
