---
- name: In developments releases
  hosts: all
  tasks:
    - name: Include gwerlas.system
      ansible.builtin.include_role:
        name: gwerlas.system
      vars:
        system_retries: 5
        system_packages_upgrade: true
        system_portage_accept_keywords:
          - ~amd64
        system_portage_kernel: vanilla-kernel
        system_portage_repos_directory: /data
        system_portage_repos:
          - name: guru
        system_el_repos:
          - name: centos
            repositories:
              - id: baseos
                metalink: https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=$basearch&protocol=https,http
                gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
                gpgcheck: true
                repo_gpgcheck: false
                metadata_expire: 6h
                countme: true
                enabled: true
              - name: CentOS Stream $releasever - AppStream
                metalink: https://mirrors.centos.org/metalink?repo=centos-baseos-source-$stream&arch=source&protocol=https,http
                gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
                gpgcheck: 0
                repo_gpgcheck: 0
                metadata_expire: 6h
                countme: 1
                enabled: 1
              - id: crb
                name: CentOS Stream $releasever - CRB
                metalink: https://mirrors.centos.org/metalink?repo=centos-crb-$stream&arch=$basearch&protocol=https,http
                gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
                gpgcheck: '0'
                repo_gpgcheck: '0'
                metadata_expire: 6h
                countme: '1'
                enabled: '0'
          - name: centos-addons
            repositories:
              - id: extras-common
                name: CentOS Stream $releasever - Extras packages
                metalink: https://mirrors.centos.org/metalink?repo=centos-extras-sig-extras-common-$stream&arch=$basearch&protocol=https,http
                gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Extras-SHA512
                gpgcheck: true
                repo_gpgcheck: false
                metadata_expire: 6h
                countme: true
                enabled: true
          - name: epel
            repositories:
              - id: epel
                name: Extra Packages for Enterprise Linux $releasever
                metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
                gpgcheck: true
                gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever
                enabled: true
