---
- name: Verify role for Stream distributions
  hosts: all
  tasks:
    - name: Rsync
      ansible.posix.synchronize:
        src: verify.yml
        dest: /tmp/verify.yml

    - name: Time synchronisation
      when: ansible_service_mgr == 'systemd'
      ansible.builtin.command:
        cmd: timedatectl
      register: result
      until: "'synchronized: yes' in result.stdout"
      changed_when: false

    - name: Time synchronisation
      when: ansible_service_mgr == 'openrc'
      ansible.builtin.command:
        cmd: chronyc sourcestats
      changed_when: false

- name: Check for the Guru Gentoo overlay
  hosts: gentoo
  tasks:
    - name: Check for file
      ansible.builtin.stat:
        path: /data/guru
      register: result
      failed_when: not result.stat.exists
