---
- name: Facts - Checks
  when: ansible_os_family is undefined
  ansible.builtin.fail:
    msg: Ansible facts must be gathered

- name: Facts - Local variables
  ansible.builtin.include_vars: "{{ item }}"
  vars:
    dir:
      - "{{ role_path }}/vars/"
    flavors:
      - "{{ ansible_pkg_mgr }}"                                                         # apt,           dnf,          etc.
      - "{{ ansible_service_mgr }}"                                                     # openrc
      - "{{ ansible_os_family | lower }}-like"                                          # debian-like,   redhat-like,  etc.
      - "{{ ansible_distribution | lower }}"                                            # debian,        fedora,       etc.
      - "{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}-like"  # redhat7-like,  redhat8-like, etc.
      - "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}"    # debian10,      debian11
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}" # ubuntu-bionic, ubuntu-focal
    ext:
      - .yml
  with_fileglob: |
    {{
      dir |
      product(current_profiles + flavors) |
      map('join') |
      product(ext) |
      map('join')
    }}

- name: Facts - Global
  vars:
    packages_keys: |
      {{
        ( system_packages_add_by_key + users_shells
        + (current_profiles_values | selectattr('packages', 'defined') | map(attribute='packages'))
        + (current_network_types | selectattr('packages', 'defined') | map(attribute='packages'))
        + (system_manage_time | ternary([time_backend_name], []))
        + (system_packages_upgrade_unattended | ternary(['unattended-upgrades'], []))
        + (system_ca_certificates | length > 0) | ternary(['ca-certificates'], [])
        + (system_manage_storages | ternary(['parted'], []))
        + (system_manage_lvm | ternary(['lvm2'], []))
        + (system_manage_firewall | ternary(['firewalld'], []))
        ) | flatten | unique | difference(masks.packages | default([]))
      }}
    packages: |
      {{
        (family_packages | default({})) |
        combine(distro_packages | default({})) |
        combine(release_packages | default({}))
      }}
    services_keys: |
      {{
        ( (current_profiles_values | selectattr('services', 'defined') | map(attribute='services'))
        + (system_manage_time | ternary(time_backend.services, []))
        ) | flatten | unique
      }}
    services: |
      {{
        (family_services | default({})) |
        combine(distro_services | default({})) |
        combine(release_services | default({}))
      }}
  ansible.builtin.set_fact:
    cacheable: true
    system_mounts: |
      {{
        ((
          (
            (system_storages_partitions | selectattr('state', 'undefined')) +
            (system_storages_partitions | selectattr('state', 'defined') | selectattr('state', '==', 'present'))
          ) |
          to_json | from_json |
          community.general.json_query('[?mount].{
            fstype: not_null(fs_type, `ext4`),
            group: not_null(group, `root`),
            mode: not_null(mode, `0755`),
            owner: not_null(owner, `root`),
            path: mount,
            resize: not_null(resize, `true`),
            src: join(``, [device, to_string(not_null(number, `1`))])
          }')
        ) + (
          (
            (system_storages_lvol | selectattr('state', 'undefined')) +
            (system_storages_lvol | selectattr('state', 'defined') | selectattr('state', '==', 'present'))
          ) |
          to_json | from_json |
          community.general.json_query('[?mount].{
            fstype: not_null(fstype, `ext4`),
            group: not_null(group, `root`),
            mode: not_null(mode, `0755`),
            owner: not_null(owner, `root`),
            path: mount,
            resize: not_null(resizefs, `true`),
            src: join(`/`, [``, `dev`, `mapper`, join(`-`, [vg, lv])])
          }')
        )) | sort(attribute='path')
      }}
    system_needs_reboot: "{{ system_needs_reboot | default(false) }}"
    system_packages: |
      {{
        ( system_packages_add_by_name
        + (packages_add_by_name | default([]))
        + (packages_keys | intersect(packages.keys()) | map('extract', packages))
        + (packages_keys | difference(packages.keys()))
        ) | flatten | sort | unique
      }}
    system_shells: "{{ users_shells }}"
    system_services_dict: "{{ services }}"
    system_services: |
      {{
        ( (services_keys | intersect(services.keys()) | map('extract', services))
        + (services_keys | difference(services.keys()))
        ) | flatten | sort | unique
      }}

- name: Facts - Installed packages
  ansible.builtin.package_facts:

- name: Unconfined facts
  when: not in_container
  block:
    - name: Facts - Stat /sys/firmware/efi
      ansible.builtin.stat:
        path: /sys/firmware/efi
      register: result

    - name: Facts - Autodetections
      ansible.builtin.set_fact:
        system_uptime: "{{ (ansible_date_time.epoch | int) - ansible_uptime_seconds }}"
        system_boot_mode: "{{ result.stat.exists | ternary('efi', 'pc') }}"
        cacheable: true

    - name: Facts - Autodetect installed kernel package
      when:
        - ansible_pkg_mgr == 'portage'
        - system_portage_kernel == 'auto'
      vars:
        current_kernel: |
          {{
            ansible_facts.packages.values() |
            flatten |
            json_query("[?category=='sys-kernel' && (name.contains(@, '-kernel') || name.contains(@, '-sources'))]") |
            last
          }}
      ansible.builtin.set_fact:
        system_portage_kernel: "{{ current_kernel.name }}"
        system_portage_kernel_provider: |-
          {{
            current_kernel.name is match('.*-sources$') |
            ternary('genkernel', 'dist')
          }}
        cacheable: true
