---
- name: Networks - Load variables
  when: default_network_backend_name is undefined
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Hosts - Local hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ system_hostname }}"
  notify: restart hostname

- name: Hosts - Fix localhost fqdn detection
  when: network_backend_name == "systemd-networkd"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    line: "hosts: mymachines files resolve [!UNAVAIL=return] myhostname dns"
    regexp: "^hosts:"

- name: Hosts - Netifrc configuration
  when: network_backend_name == "netifrc"
  become: true
  notify: restart hostname
  block:
    - name: Hosts - Netifrc - Remove /etc/hostname
      ansible.builtin.file:
        path: /etc/hostname
        state: absent

    - name: Hosts - Netifrc - Domain name
      when: system_domain is defined
      ansible.builtin.lineinfile:
        path: /etc/conf.d/net
        line: 'dns_domain_lo="{{ system_domain }}"'
        regex: ^dns_domain_lo=
        create: true
        group: wheel
        mode: "0644"

- name: /etc/hosts
  vars:
    local_hostnames: |
      {{
        ( [system_hostname] + system_hostnames ) |
        product(['', '.' + system_domain]) |
        map('join')
      }}
    local_ips:
      - ip: "127.0.0.1"
        names: ['localhost']
      - ip: "127.0.1.1"
        names: "{{ local_hostnames }}"
      - ip: "::1"
        names: "{{ ['localhost', 'ip6-localhost', 'ip6-loopback'] + local_hostnames }}"
    etc_hosts: "{{ local_ips + system_hosts }}"
  block:
    - name: Hosts - Display hosts for debugging
      ansible.builtin.debug:
        var: etc_hosts
        verbosity: 1

    - name: Hosts - Names in /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ '{:<15}'.format(host.ip) }} {{ host.names | join(' ') }}"
        regexp: "^{{ host.ip | regex_escape }}\\s"
      loop: "{{ etc_hosts }}"
      loop_control:
        loop_var: host
      notify: restart hostname
