---
- name: SSHd
  when: system_manage_sshd
  tags:
    - ssh
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/remote-access/sshd.yml"

- name: SSHd hosts keys
  when: system_sshd_host_keys is defined
  tags:
    - ssh
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/remote-access/sshd-host-keys.yml"
