---
argument_specs:
  main:
    short_description: The main entry point which calls the other tasks if needed / asked.
    options:
      system_manage_sudo:
        type: bool
        default: "false for containers"
        description: Enable/Disable sudo management.
      system_manage_hosts:
        type: bool
        default: "false for containers"
        description: Enable/Disable hosts names management.
      system_manage_proxies:
        type: bool
        default: "false if any proxy setting given"
        description: Enable/Disable proxies settings.

  hosts:
    short_description: Configure system hostname and /etc/hosts file.
    options:
      system_domain:
        description: Local domain name.
      system_hostname:
        default: "{{ inventory_hostname }}"
        description: Local host name.
      system_hostnames:
        type: list
        elements: str
        default: "[]"
        description: List of additional names for local host.
      system_hosts:
        type: list
        elements: dict
        default: "[]"
        description: List of external custom hosts.

  networks:
    short_description: Configure network interfaces.
    options:
      system_networks_check_mode:
        type: str
        default: files
        description: Which mode to check if an interface have to be configured or not
        choices:
          - facts
          - files
      system_networks_interfaces:
        type: list
        elements: dict
        default: "[]"
        description: List of interfaces to manage
      system_networks_interfaces_prune:
        type: bool
        default: "true"
        description: Remove the unmanaged interfaces
      system_networks_restart_handler:
        type: str
        default: reboot
        choices:
          - restart network service
          - skip
          - reboot
        description: Choose the manner to restart the network

  packages:
    short_description: Configure the package manager and install/update the system
    options:
      system_scripts_path:
        default: /usr/local/bin
        description: Path location for our scripts
      system_packages_add_by_key:
        type: list
        elements: str
        default: "[]"
        description: List of packages names to install on the node (can be translated).
      system_packages_add_by_name:
        type: list
        elements: str
        default: "[]"
        description: List of raw packages names to install on the node.
      system_packages_cache_age:
        type: int
        default: 7
        description: The maximum accepted cache age (in days)
      system_packages_upgrade:
        type: bool
        default: false
        description: Ask a system update, default to false to permit playbooks idempotence.
      system_profile:
        default: server
        description: Type of the node
        choices:
          - desktop
          - desktop/gnome
          - server

  proxies:
    short_description: Configure network proxies
    options:
      system_http_proxy:
        default: "null"
        description: Proxy server for HTTP connections
      system_https_proxy:
        default: "null"
        description: Proxy server for HTTPs connections
      system_ftp_proxy:
        default: "null"
        description: Proxy server for FTP connections
      system_no_proxy:
        default: "null"
        description: Comma-separated list of domain extensions proxy should not be used for

  reboot:
    short_description: Reboot the system if needed
    options:
      system_scripts_path:
        default: /usr/local/bin
        description: Path location for our scripts

  sudo:
    short_description: Configure sudo rules.
    options:
      system_sudo_defaults:
        type: list
        elements: str
        default: "[]"
        description: Sudoers 'Defaults' parameter list.
      system_sudo_nopasswd:
        type: bool
        default: "true"
        description: Add NOPASSWD to system_sudo_group.
      system_sudo_group:
        type: str
        default: "'sudo' for Debian like distros, 'wheel' otherwise"
        description: Name of the group with all permissions.

  storages:
    short_description: Create block devices and LVM, format and mount them.
    options:
      system_storages_partitions:
        type: list
        elements: dict
        default: "[]"
        description: Configure block device partitions.
      system_storages_lvol:
        type: list
        elements: dict
        default: "[]"
        description: Configure LVM logical volumes.
      system_storages_vg:
        type: list
        elements: dict
        default: "[]"
        description: Configure LVM volume groups.

  time:
    short_description: Time and date management.
    options:
      system_time_backend:
        choices:
          - chrony
          - ntp
          - systemd-timesyncd
        description: Name of the backend to use.

  users:
    short_description: Users and groups management.
    options:
      system_users:
        type: list
        elements: dict
        default: "[]"
        description: List of system users.
      system_users_groups:
        type: list
        elements: dict
        default: "[]"
        description: List of system groups.
      system_users_admin_group:
        type: str
        default: "'adm' for Debian like distros, 'wheel' otherwise"
        description: Name of the admin group.

  users/linger:
    short_description: Enable linger for users managed by systemd
    options:
      system_user:
        type: dict
        description: System user object (see ansible.builtin.user for properties)

  users/zsh:
    short_description: ZSH configuration.
    options:
      system_zsh_files:
        type: list
        elements: str
        default: "[]"
        description: List of raw files to copy in `/etc/skel`.
      system_zsh_templates:
        type: list
        elements: str
        default: "[]"
        description: List of templated files to copy in `/etc/skel`.
