---
- name: Become root
  become: true
  vars:
    config: "{{ sshd_config | combine(system_sshd_config) }}"
  block:
    - name: Remote access - SSHd - Modular configuration directory
      when: key in config
      ansible.builtin.file:
        state: directory
        path: "{{ config[key] }}"
        mode: "0700"
      loop:
        - Include
        - include
      loop_control:
        loop_var: key

    - name: Remote access - SSHd - Configuration file
      vars:
        list_separated_by_comma:
          - AuthenticationMethods
          - CASignatureAlgorithms
          - Ciphers
          - HostbasedAcceptedKeyTypes
          - HostKeyAlgorithms
          - KexAlgorithms
          - MACs
          - PubkeyAcceptedKeyTypes
      ansible.builtin.template:
        src: ssh/sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: "0600"
        validate: sshd -T -f %s
      notify: restart sshd
