---
- name: Converge customization
  hosts: all
  tasks:
    - name: Include gwerlas.system
      ansible.builtin.include_role:
        name: gwerlas.system
      vars:
        system_profile: desktop/gnome
        system_http_proxy: http://192.168.122.1:3128
        system_https_proxy: "{{ system_http_proxy }}"
        system_ftp_proxy: "{{ system_http_proxy }}"
        system_sshd_host_keys:
          ecdsa:
            src: ecdsa.key
          ecdsa_public:
            src: ecdsa.pub
          ed25519:
            content: "{{ lookup('ansible.builtin.file', 'ed25519.key') }}"
          ed25519_public:
            content: "{{ lookup('ansible.builtin.file', 'ed25519.pub') }}"
          rsa:
            src: rsa.key
          rsa_public:
            content: "{{ lookup('ansible.builtin.file', 'rsa.pub') }}"
        system_users:
          - name: console   # Console login: console / console
            password: "$6$x6sBonxCllPu$B80ZiesqnGAEoAU2lvWdzO8gkEntv9.cSCtNQNd6fX0uW7AgKCIoQKgVu3rsthx5RGGIxsl21OptxcHSiovc41"
