---
- name: Portage - Kernel - Copy current saved config
  become: true
  vars:
    current: /etc/portage/savedconfig/sys-kernel/{{ system_portage_kernel }}-{{ system_kernel }}
  ansible.builtin.copy:
    dest: /etc/portage/savedconfig/sys-kernel/{{ system_portage_kernel }}
    src: "{{ savedconfig | default(current) }}"
    remote_src: true
    group: portage
    mode: "0664"
