---
- name: Portage - Kernel - Dist - Get the latest kernel version
  check_mode: false
  ansible.builtin.command:
    cmd: portageq best_visible / sys-kernel/{{ system_portage_kernel }}
  register: result
  changed_when: false

- name: Portage - Kernel - Dist - Latest available kernel fact
  ansible.builtin.set_fact:
    system_latest_kernel: "{{ result.stdout | regex_replace('.*-([0-9.]+).*', '\\1') }}"

- name: Portage - Kernel - Dist - Get the latest version
  when:
    - system_packages_upgrade
    - ansible_kernel is not match(system_latest_kernel | regex_escape)
  block:
    - name: Portage - Kernel - Dist - Get saved config
      ansible.builtin.stat:
        path: /etc/portage/savedconfig/sys-kernel/{{ system_portage_kernel }}
      register: kernel_savedconfig

    - name: Portage - Kernel - Dist - Saved config
      when: not kernel_savedconfig.stat.exists
      block:
        - name: Portage - Kernel - Dist - Get current saved config
          ansible.builtin.stat:
            path: /etc/portage/savedconfig/sys-kernel/{{ system_portage_kernel }}-{{ system_kernel }}
          register: current_savedconfig

        - name: Portage - Kernel - Dist - Use current saved config
          vars:
            savedconfig_method: |
              {{
                current_savedconfig.stat.exists |
                ternary(
                  'copy-savedconfig',
                  'make-localmodconfig'
                )
              }}
          ansible.builtin.include_tasks: "{{ role_path }}/tasks/packages/portage/kernel/{{ savedconfig_method }}.yml"

- name: Portage - Kernel - Dist - Dist kernel packages
  become: true
  community.general.portage:
    update: "{{ system_packages_upgrade }}"
    package:
      - sys-kernel/linux-firmware
      - sys-kernel/{{ system_portage_kernel }}
      - virtual/dist-kernel
  notify:
    - emerge @module-rebuild
    - grub-mkconfig
    - reboot

- name: Portage - Kernel - Dist - Symlink
  become: true
  ansible.builtin.file:
    src: linux-{{ system_latest_kernel }}-gentoo-dist
    dest: /usr/src/linux
    state: link
    follow: false
    force: true
  notify:
    - emerge @module-rebuild
