---
- name: Verify facts
  hosts: all
  gather_facts: false
  tasks:
    - name: Assertions
      ansible.builtin.assert:
        that:
          - system_mounts | length > 0
          - system_needs_reboot is false
          - system_packages | length > 0
          - system_shells | length == 0
