---
system_users_admin_group: administrators

system_users:
  - name: drno
    state: absent
    authorized_keys:
      - key: ssh-rsa BBBB test
  - name: console   # Console login: console / console
    password: "$6$x6sBonxCllPu$B80ZiesqnGAEoAU2lvWdzO8gkEntv9.cSCtNQNd6fX0uW7AgKCIoQKgVu3rsthx5RGGIxsl21OptxcHSiovc41"
  - name: jane
    comment: System administrator
    group: "{{ system_users_admin_group }}"
    groups:
      - "{{ system_sudo_group }}"
      - my_team
    authorized_keys:
      - key: ssh-rsa AAAA test
    shell: /bin/zsh
  - name: john
    group: users
  - name: my_service
    shell: /usr/bin/nologin
    system: true
    state: present
    uid: 207

system_users_groups:
  - name: my_company
  - name: villains
    state: absent
