---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux
    image: gwerlas/ansible-guest-archlinux
    pre_build_mage: true
    volumes: &volumes
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: gentoo
    image: gwerlas/ansible-guest-gentoo
    pre_build_mage: true
    volumes: *volumes

  # Debian like
  - name: bullseye
    image: gwerlas/ansible-guest-debian:bullseye
    pre_build_mage: true
    volumes: *volumes
  - name: bookworm
    image: gwerlas/ansible-guest-debian:bookworm
    pre_build_mage: true
    volumes: *volumes
  - name: trixie
    image: gwerlas/ansible-guest-debian:trixie
    pre_build_mage: true
    volumes: *volumes
  - name: jammy
    image: gwerlas/ansible-guest-ubuntu:22.04
    pre_build_mage: true
    volumes: *volumes
  - name: noble
    image: gwerlas/ansible-guest-ubuntu:24.04
    pre_build_mage: true
    volumes: *volumes

  # RedHat like
  - name: centos9s
    image: gwerlas/ansible-guest-centos:stream9
    pre_build_mage: true
    volumes: *volumes
  - name: alma9
    image: gwerlas/ansible-guest-almalinux:9
    pre_build_mage: true
    volumes: *volumes
  - name: fedora40
    image: gwerlas/ansible-guest-fedora:40
    pre_build_mage: true
    volumes: *volumes
  - name: fedora41
    image: gwerlas/ansible-guest-fedora:41
    pre_build_mage: true
    volumes: *volumes
lint: ansible-lint
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
verifier:
  name: ansible
