---
- name: CA
  tags:
    - ca
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/ca.yml"

- name: Remote access
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/remote-access.yml"

- name: Firewall
  tags:
    - firewall
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/firewall.yml"

- name: Hosts
  tags:
    - hosts
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/hosts.yml"

- name: Packages
  tags:
    - ca
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/packages.yml"

- name: Storages
  when: system_manage_storages
  tags:
    - storages
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/storages.yml"

- name: Time
  tags:
    - time
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/time.yml"

- name: System restarts
  when: not in_container
  tags:
    - always
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/restarts.yml"
