---
- name: APT
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/apt.yml"

- name: Portage
  when: ansible_pkg_mgr == 'portage'
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/portage.yml"

- name: Restart the Display Manager
  listen:
    - restart display-manager
  when: ansible_service_mgr == "openrc"
  become: true
  ansible.builtin.service:
    name: display-manager
    state: restarted

- name: Update Grub configuration
  listen:
    - genkernel
    - grub-mkconfig
  become: true
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: true
