---
- name: APT
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/apt.yml"

- name: Portage
  when: ansible_pkg_mgr == 'portage'
  ansible.builtin.import_tasks: "{{ role_path }}/handlers/portage.yml"

- name: Restart the Display Manager
  listen:
    - restart display-manager
  become: true
  ansible.builtin.service:
    name: "{{ lookup('service', 'gdm') }}"
    state: restarted

- name: Update Grub configuration
  listen:
    - genkernel
    - grub-mkconfig
  become: true
  vars:
    output: |-
      {{
        ('GRUB_CFG' in ansible_env) |
        ternary(
          ansible_env.GRUB_CFG,
          '/boot/grub/grub.cfg'
        )
      }}
  ansible.builtin.command:
    cmd: grub-mkconfig -o {{ output }}
  changed_when: true
