---
- name: SSH service restart
  listen:
    - restart sshd
  become: true
  ansible.builtin.service:
    name: "{{ lookup('service', 'sshd') }}"
    state: restarted

- name: Reset SSH connection
  listen:
    - restart sshd
  ansible.builtin.meta: reset_connection
