---
- name: Reboot is needed
  listen:
    - skip
    - reboot
  ansible.builtin.set_fact:
    system_needs_reboot: true

- name: Restart network
  listen:
    - restart network service
  become: true
  ansible.builtin.service:
    name: "{{ default_networks.service_name }}"

- name: Skip restart
  listen:
    - skip
  ansible.builtin.debug:
    msg: You skipped the network restart or the reboot !

- name: Reload OpenRC
  listen:
    - reload init system
  when: ansible_service_mgr == "openrc"
  become: true
  ansible.builtin.command:
    cmd: telinit u
  changed_when: true

- name: Reload systemd
  listen:
    - reload init system
  when: ansible_service_mgr == "systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reboot
  listen:
    - reboot
  become: true
  ansible.builtin.reboot:
    reboot_timeout: "{{ system_reboot_timeout }}"
    msg: Reboot initiated by the playbook {{ ansible_play_name }}

- name: Reboot completed
  listen:
    - reboot
  ansible.builtin.set_fact:
    system_needs_reboot: false

- name: Gather facts again
  listen:
    - restart network service
    - reboot
  ansible.builtin.gather_facts:
