---
- name: Time service restart
  listen:
    - restart time service
  become: true
  ansible.builtin.service:
    name: "{{ service }}"
    state: restarted
  with_service: "{{ time_backend.services }}"
  loop_control:
    loop_var: service
