---
- name: Portage - Clean dependencies
  become: true
  community.general.portage:
    depclean: true
  notify: emerge --newuse

- name: Portage - Clean distfiles
  become: true
  ansible.builtin.command:
    cmd: eclean-dist --deep
  register: result
  changed_when: not 'Your distfiles directory was already clean.' in result.stdout

- name: Unconfined systems
  when: not in_container
  block:
    - name: Portage - Installed/updated packages during this boot
      ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/packages/portage/installed-this-boot.yml"

    # If cpuid2cpuflags has been updated, its output may change now so we have to
    # update /etc/portage/make.conf as well and rebuild the impacted packages if
    # required.
    - name: Portage - CPU flags
      when: "'app-portage/cpuid2cpuflags' in installed_this_boot.stdout"
      ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/package-managers/portage/make.conf.yml"

- name: Portage - Etc update
  become: true
  ansible.builtin.command:
    cmd: etc-update --automode -5
  register: result
  changed_when: result.stdout_lines | length > 2
