---
- name: Packages - Update package list
  when: system_packages_upgrade
  ansible.builtin.include_tasks:
    file: "{{ package_task }}"
  with_first_found:
    - files:
        - update.yml
      paths:
        - "{{ role_path }}/tasks/package-managers/{{ ansible_pkg_mgr }}"
        - "{{ role_path }}/tasks/package-managers/other"
  loop_control:
    loop_var: package_task

- name: Packages - Distribution upgrade
  when: system_packages_upgrade
  ansible.builtin.include_tasks:
    file: "{{ package_task }}"
  with_first_found:
    - files:
        - dist-upgrade.yml
      paths:
        - "{{ role_path }}/tasks/packages/{{ ansible_pkg_mgr }}"
        - "{{ role_path }}/tasks/packages/other"
  loop_control:
    loop_var: package_task

- name: Packages - Install - Show the list
  ansible.builtin.debug:
    var: system_packages
    verbosity: 1

- name: Packages - Installation
  ansible.builtin.include_tasks:
    file: "{{ package_task }}"
  with_first_found:
    - files:
        - install.yml
      paths:
        - "{{ role_path }}/tasks/packages/{{ ansible_pkg_mgr }}"
        - "{{ role_path }}/tasks/packages/other"
  loop_control:
    loop_var: package_task
