---
- name: Portage - Needs update
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/package-managers/needs-update.yml"

- name: Portage - Cache update
  when: system_cache_needs_update
  tags:
    - molecule-idempotence-notest
  become: true
  community.general.portage:
    sync: "{{ 'web' if system_manage_proxies else true }}"
  register: result
  until: result.failed == false
  retries: "{{ system_retries }}"

# Update portage as the official recommendation:
# https://wiki.gentoo.org/wiki/Portage#Updating_Portage
- name: Portage - Upgrade Portage itself
  become: true
  community.general.portage:
    update: "{{ system_packages_upgrade }}"
    oneshot: true
    package: sys-apps/portage
